apiVersion: v2
name: msa-platform
description: index + market + post
type: application
version: 0.1.0
appVersion: "1.0.0"

# 의존하는 dependency chart 목록
dependencies:
  - name: index-app
    version: "0.1.0"
    # "file://하위 chart의 경로 작성"
    repository: "file://charts/index"
    # 하위 chart를 무조건 포함하는 것이 아니고 조건부로 포함하겠다는 의미(values.yaml에 해당 값이 true이면 포함)
    condition: index-app.enabled
  - name: market-app
    version: "0.1.0"
    repository: "file://charts/market"
    condition: market-app.enabled
  - name: post-app
    version: "0.1.0"
    repository: "file://charts/post"
    condition: post-app.enabled