
index-app:
  replicaCount: 2
  image:
    tag: "1.0"
  service:
    port: 80
  containerPort: 80
  enabled: true

market-app:
  replicaCount: 2
  image:
    tag: "1.0"
  service:
    port: 8000
  containerPort: 8000
  enabled: false

post-app:
  replicaCount: 2
  image:
    tag: "1.0"
  service:
    port: 8000
  containerPort: 8000
  enabled: true
  