---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: market-app
  template:
    metadata:
      labels:
        app: market-app
    spec:
      containers:
      - name: market-ctn
        image: tkddn3901/market-app:1.0 # ◄── 마켓 정품 이미지 포획!
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
       